application:
  subdomain: pocket-id
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://pocket-id:1411/
services:
  pocket-id:
    # ghcr.io/pocket-id/pocket-id:v2.0.1
    # upstream: ghcr.io/pocket-id/pocket-id:v2.10.0
    image: registry.lazycat.cloud/czyt/pocket-id/pocket-id:049cea344eba31ef
    environment:
{{if .U.enable_custom_domain}}
      - APP_URL=https://{{.U.custom_domain}}
{{else}}
      - APP_URL=http://${{.S.AppDomain}}
{{end}}
      - TRUST_PROXY={{.U.trust_proxy}}
      - MAXMIND_LICENSE_KEY={{.U.maxmind_license_key}}
      - ENCRYPTION_KEY={{stable_secret "pocket_id_encryption_x"}}
      - PUID=1000
      - PGID=1000
    binds:
      - /lzcapp/var/data:/app/data
    healthcheck:
      test:
        - CMD-SHELL
        - /app/pocket-id healthcheck
      start_period: 30s
