package: lazycat.community.app.pocket-id
version: 2.11.0
name: Pocket ID
description: A simple and easy-to-use OIDC provider
min_os_version: 1.5.0
homepage: https://github.com/pocket-id/pocket-id
author: pocket-id
locales:
  en:
    name: Pocket ID
    description: A simple and easy-to-use OIDC provider
  zh:
    name: Pocket ID
    description: 一个简单易用的 OIDC 提供商
